#!/usr/bin/env python3
"""Was wir weitergeben, unter welcher Lizenz, und wie wir die Auflagen erfuellen.

    python tools/redistribution_report.py > docs/redistribution.md

WARUM ERZEUGT UND NICHT GESCHRIEBEN:
Eine von Hand gepflegte Lizenzuebersicht ist nach dem naechsten Pin-Wechsel
falsch, und niemand merkt es. Diese hier liest gappa-pin.json, matiec-pin.json
und mirror-pin.json - dieselben Dateien, nach denen gebaut und gespiegelt wird.
Weicht sie ab, weicht der Bau ab.

Sie ist die Unterlage fuer eine lizenzfachliche Abnahme (#323, Punkt 5). Sie
ist KEINE Rechtsberatung und behauptet auch nicht, vollstaendig zu sein - was
sie nicht abdeckt, steht am Ende.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _pin(name: str) -> dict:
    return json.loads((ROOT / name).read_text(encoding="utf-8-sig"))


def zeilen() -> list[str]:
    z: list[str] = []
    w = z.append
    w("# What we redistribute, and under which terms")
    w("")
    w("Generated by `tools/redistribution_report.py` from the pin files the")
    w("build and the mirror actually use. Editing this page by hand would make")
    w("it a second, drifting claim; change the pins instead.")
    w("")
    w("This is **not legal advice**. It is the dossier for a licence review:")
    w("every artifact we publish, what its licence asks of a distributor, and")
    w("what we do about it. What it does *not* cover is listed at the end.")
    w("")
    w("---")
    w("")
    w("## 1. Software we build ourselves")
    w("")
    w("We compile these from pinned sources and publish the result. That makes")
    w("us a distributor of the compiled work *and* of the libraries it links.")
    w("")
    for datei, kurz in (("gappa-pin.json", "Gappa"), ("matiec-pin.json", "matiec")):
        p = _pin(datei)
        b = p["windows_build"]
        kennung = p.get("version") or p["revision"][:7]
        w(f"### {kurz} {kennung} (Windows x86_64)")
        w("")
        w(f"- **Licence:** {b['tool_licence']['spdx']}")
        w(f"- **Source:** {list(p['source'].values())[0]['url']}")
        w(f"  (sha256 `{list(p['source'].values())[0]['sha256'][:32]}…`)")
        w(f"- **Upstream:** {p['upstream_project']}")
        w("- **Linked dynamically**, libraries shipped beside the binary:")
        w("")
        w("  | Library | From | Licence |")
        w("  |---|---|---|")
        for dll, meta in b["runtime_dlls"].items():
            w(f"  | `{dll}` | {meta['msys2_package']} | {meta['msys2_licenses']} |")
        w("")
        w("- **How the obligations are discharged:**")
        w("    - full licence texts inside the package, under `licenses/`;")
        w("    - `NOTICE.txt` naming every bundled library and its licence;")
        w("    - `SOURCES.txt` naming where each compiled source came from;")
        w("    - the source archive published in the same directory as the binary;")
        w("    - dynamic linking, so an LGPL library can be replaced in place.")
        w("")
        w(f"  Why dynamic: {b['_why_dynamic']}")
        w("")
    w("### zqel itself")
    w("")
    w("The standalone builds embed a Python runtime, the packages Nuitka")
    w("reports as included, and Z3's native library. The package carries a")
    w("`NOTICE.txt` generated from Nuitka's own report and from the licence")
    w("metadata each package publishes — not from a hand-kept list. Licence")
    w("texts land under `licenses/`.")
    w("")
    w("---")
    w("")
    w("## 2. Software we mirror unchanged")
    w("")
    w("Byte-for-byte copies of upstream releases. We do not repack them:")
    w("repacking would turn passing something on into modifying it, and")
    w("different obligations would apply. Each copy has a `.notice.txt` beside")
    w("it naming origin, checksum and licence.")
    w("")
    m = _pin("mirror-pin.json")
    for name, meta in m["tools"].items():
        w(f"### {name} {meta['version']}")
        w("")
        w(f"- **Licence:** {meta['spdx']}")
        w(f"- **Upstream:** {meta['upstream']}")
        w(f"- **Artifacts:** {len(meta['artifacts'])}")
        for art_name, art in meta["artifacts"].items():
            w(f"    - `{art_name}` — sha256 `{art['sha256'][:32]}…`")
        drin = set()
        for art in meta["artifacts"].values():
            drin.update(art.get("licence_files_inside", []))
        if drin:
            w("- **Licence texts inside the archive** (verified on every mirror run):")
            for f in sorted(drin):
                w(f"    - `{f}`")
        if meta.get("licence_sidecar"):
            w(f"- **Licence text shipped beside it:** `{meta['licence_sidecar']['name']}`")
        w("")
        w(f"  {meta['_licence_note']}")
        w("")
    w("---")
    w("")
    w("## 3. What this dossier does not cover")
    w("")
    w("- **The transitive dependency closure of the Windows build machine.**")
    w("  `tools/windows/msys2.lock.json` pins the packages we install and the")
    w("  owners of the DLLs we ship. Everything those pull in is not pinned.")
    w("- **A legal reading.** Nobody with a licence qualification has looked at")
    w("  this. The obligations above are what the licence texts say, read by an")
    w("  engineer.")
    w("- **cvc5's exact binary configuration.** We mirror the release variant")
    w("  without `-gpl` in its name. Whether that build links GMP statically,")
    w("  and what that means for the LGPL relink provision, has not been")
    w("  established by inspecting the binary.")
    w("- **Anything distributed outside `dl.zqel.org` and the forgejo package")
    w("  registry.**")
    return z


if __name__ == "__main__":
    sys.stdout.write("\n".join(zeilen()) + "\n")
